//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horari.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrerarevoe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public carrerarevoe()
        {
            this.asignaturacarrera = new HashSet<asignaturacarrera>();
        }
    
        public int idCarreraRevoe { get; set; }
        public int carrera { get; set; }
        public int revoe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignaturacarrera> asignaturacarrera { get; set; }
        public virtual carrera carrera1 { get; set; }
        public virtual revoe revoe1 { get; set; }
    }
}
