//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horari.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public curso()
        {
            this.horario = new HashSet<horario>();
        }
    
        public int idCurso { get; set; }
        public string grupo { get; set; }
        public int cuatrimestre { get; set; }
        public int turno { get; set; }
        public int asignatura { get; set; }
        public string control { get; set; }
    
        public virtual asignaturacarrera asignaturacarrera { get; set; }
        public virtual cuatrimestre cuatrimestre1 { get; set; }
        public virtual profesor profesor { get; set; }
        public virtual grupo grupo1 { get; set; }
        public virtual turno turno1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<horario> horario { get; set; }
    }
}
