//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horari.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class disponibilidad
    {
        public long idHorario { get; set; }
        public string profesor { get; set; }
        public long dia { get; set; }
        public string horas { get; set; }
    
        public virtual profesor profesor1 { get; set; }
        public virtual semana semana { get; set; }
    }
}
