//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horari.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario
    {
        public long idHorario { get; set; }
        public int curso { get; set; }
        public long inicio { get; set; }
        public long fin { get; set; }
        public long dia { get; set; }
    
        public virtual curso curso1 { get; set; }
        public virtual hora hora { get; set; }
        public virtual hora hora1 { get; set; }
        public virtual semana semana { get; set; }
    }
}
